### ISSUE TITLE
HoverDocs not working

### ISSUE THREAD

**Issue by kotykd** [WyattSL/greyscript#13]
So I hovered over multiple different functions like print, computer.File, format_columns, etc and they aren't showing the HoverDocs, I think this is in every update after 1.6.5, so starting at 1.7.1

**Comment by WyattSL** [comment]
Hello,

Could you provide example code, and indicate at which section it doesn't work?

Thanks!

**Comment by Patrick-van-Halm** [comment]
Also what version are you currently running?

**Comment by kotykd** [comment]
> 
> 
> Hello,
> 
> Could you provide example code, and indicate at which section it doesn't work?
> 
> Thanks!

It just doesn't work with any code that I hover over.



> 
> 
> Also what version are you currently running?

I tried 1.6.5 and all the ones up to the latest, so all the 1.7.x ones.

**Comment by Patrick-van-Halm** [comment]
I am running v1.7.5 and this works on my end. https://i.imgur.com/cEprLW4.png

You could try and do:
1. Ctrl + Shift + P.
2. Type Show Hover.
3. Press enter.
4. Do Ctrl + Space.
5. Hover over something and the hover info should appear.

Let me know if it fixed it :)

**Comment by Patrick-van-Halm** [comment]
No new response received in a while so issue shall be closed.
