### ISSUE TITLE
Weird autocomplete issue

### ISSUE THREAD

**Issue by kotykd** [WyattSL/greyscript#21]
Hey, whenever I have, for example, a for loop like "for f in list", if I type f and a ".", it sometimes autocompletes to "false." even when I don't press Tab or Enter. I don't know how to check if it's reproducible so, if you need any help, just let me know then I will try to provide more details.

**Comment by WyattSL** [comment]
I'm not quite able to reproduce this myself: it does show `false` in the autocomplete options (which is expected) it doesn't autofill it unless I press enter.

If vscode is doing autocompletes without user interaction, I think that might be more of an underlying problem with vscode.

**Comment by kotykd** [comment]
Hmm, that is strange, but thanks for checking anyway. Luckily it's not too terrible as I can just hit space then hit backspace then type it out normally, but still kind of strange.
